[package]
name = "netavark"
version = "0.0.1"
edition = "2018"
authors = ["github.com/containers"]
description = "A container network stack"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.4"
